name: butils_example
description: Demonstrates the usage of butils.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Depend on the local package
  butils:
    path: ../
  flutter_math_fork: ^0.7.4

flutter:
  uses-material-design: true
