name: butils
description: A collection of standard utility widgets for Flutter applications.
version: 1.0.0
homepage: https://example.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_math_fork: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
